language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
- yarn coverage
- yarn coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_4ed3bd6cdd56_key -iv $encrypted_4ed3bd6cdd56_iv
  -in deploy_key.enc -out deploy_key -d
